version:  '3'
services:
  scipy-notebook:
      image: jupyter/scipy-notebook
      ports:
        - 8888:8888
      container_name: jupyter_scipy
      command: "start-notebook.sh --NotebookApp.allow_origin='*' --NotebookApp.password=test --NotebookApp.token=test --NotebookApp.disable_check_xsrf=True --no-browser"
      user: root
      environment:
        GRANT_SUDO: "yes"

